CREATE TABLE ARTICLE
(
    ID bigint PRIMARY KEY NOT NULL IDENTITY,
    URL varchar(255)
);
CREATE UNIQUE INDEX UNIQUE_URL ON ARTICLE (URL);

CREATE TABLE SNAPSHOT
(
    ID bigint PRIMARY KEY NOT NULL IDENTITY,
    ARTICLE_ID bigint,
    CONTENT varchar(50000),
    TIME timestamp,
    CONSTRAINT FK_SNAPSHOT FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE (ID)
);