server.port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

spring.servlet.multipart:
  max-file-size: 100000MB
  max-request-size: 100000MB

spring.data.mongodb:
  host: "mongodb"
  port: 27017

---
spring.profiles: local

eureka.client.enabled: false

spring.data.mongodb:
  host: "192.168.99.100"
  port: 27017