server.port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

spring.servlet.multipart:
  max-file-size: 100000MB
  max-request-size: 100000MB

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000