version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    command: mongod
  hash-phone:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongodb
